"""
seed_data.py - College, Programme, and Course seed data
"""

COLLEGES = [
    {"name": "Law School", "code": "LAW", "icon": "⚖️",
     "description": "Faculty of Law and Legal Studies"},
    {"name": "College of Engineering and Applied Sciences", "code": "CEAS", "icon": "⚙️",
     "description": "Engineering, Computing, and Applied Sciences"},
    {"name": "College of Health and Environmental Sciences", "code": "CHES", "icon": "🏥",
     "description": "Health Sciences, Nursing, Pharmacy, and Environment"},
    {"name": "College of Social Sciences, Theology and Humanities", "code": "CSSTH", "icon": "📚",
     "description": "Arts, Social Sciences, Theology, and Humanities"},
    {"name": "College of Business and Management Sciences", "code": "CBMS", "icon": "💼",
     "description": "Business, Accounting, Marketing, and Management"},
]

PROGRAMMES = {
    "LAW": [
        {"name": "Bachelor of Laws (LLB)", "code": "LLB"},
        {"name": "Bachelor of Legal Studies", "code": "BLS"},
        {"name": "Diploma in Paralegal Studies", "code": "DPS"},
    ],
    "CEAS": [
        {"name": "BSc Computer Science", "code": "BSCS"},
        {"name": "BSc Civil Engineering", "code": "BSCE"},
        {"name": "BSc Electrical Engineering", "code": "BSEE"},
    ],
    "CHES": [
        {"name": "BSc Nursing Science", "code": "BSNS"},
        {"name": "BSc Environmental Science", "code": "BSES"},
        {"name": "Bachelor of Pharmacy", "code": "BPHA"},
    ],
    "CSSTH": [
        {"name": "BA Theology and Religious Studies", "code": "BATRS"},
        {"name": "BA Psychology", "code": "BAPSY"},
        {"name": "BA International Relations", "code": "BAIR"},
    ],
    "CBMS": [
        {"name": "BCom Accounting", "code": "BCACC"},
        {"name": "BCom Marketing", "code": "BCMKT"},
        {"name": "BBA Management", "code": "BBAMGT"},
    ],
}

# Courses: dict[programme_code][level] = list of 7 (name, code, description)
COURSES = {
    # ── LAW SCHOOL ──
    "LLB": {
        "1.1": [
            ("Introduction to Law", "LAW111", "Foundations of legal systems"),
            ("Legal Methods", "LAW112", "Legal reasoning and research"),
            ("Constitutional Law I", "LAW113", "Constitutional principles"),
            ("Criminal Law I", "LAW114", "Elements of criminal liability"),
            ("Communication Skills", "ENG111", "Academic writing and communication"),
            ("Introduction to Philosophy", "PHI111", "Critical thinking foundations"),
            ("University Life & Ethics", "ULE111", "Academic integrity and ethics"),
        ],
        "1.2": [
            ("Law of Contract I", "LAW121", "Formation of contracts"),
            ("Constitutional Law II", "LAW122", "Bill of rights and judicial review"),
            ("Criminal Law II", "LAW123", "Specific offences and defences"),
            ("Family Law", "LAW124", "Marriage, divorce, custody"),
            ("Legal Writing", "LAW125", "Drafting legal documents"),
            ("Sociology of Law", "SOC121", "Law and social structures"),
            ("African Customary Law", "LAW126", "Indigenous legal systems"),
        ],
        "2.1": [
            ("Law of Contract II", "LAW211", "Breach and remedies"),
            ("Law of Delict", "LAW212", "Civil wrongs and liability"),
            ("Administrative Law", "LAW213", "Government and law"),
            ("Property Law I", "LAW214", "Ownership and real rights"),
            ("Jurisprudence I", "LAW215", "Legal philosophy"),
            ("International Law I", "LAW216", "Public international law"),
            ("Legal Research Methods", "LAW217", "Advanced legal research"),
        ],
        "2.2": [
            ("Property Law II", "LAW221", "Land law and servitudes"),
            ("Law of Evidence", "LAW222", "Rules of evidence"),
            ("Company Law I", "LAW223", "Corporate formation"),
            ("Labour Law I", "LAW224", "Employment relationships"),
            ("Jurisprudence II", "LAW225", "Modern legal theories"),
            ("International Law II", "LAW226", "International humanitarian law"),
            ("Moot Court I", "LAW227", "Practical advocacy skills"),
        ],
        "3.1": [
            ("Civil Procedure I", "LAW311", "Civil litigation process"),
            ("Criminal Procedure", "LAW312", "Criminal trial process"),
            ("Company Law II", "LAW313", "Corporate governance"),
            ("Labour Law II", "LAW314", "Collective bargaining"),
            ("Tax Law I", "LAW315", "Income tax fundamentals"),
            ("Environmental Law", "LAW316", "Environmental regulation"),
            ("Human Rights Law", "LAW317", "International human rights"),
        ],
        "3.2": [
            ("Civil Procedure II", "LAW321", "Advanced civil procedure"),
            ("Law of Succession", "LAW322", "Wills and estates"),
            ("Intellectual Property Law", "LAW323", "Patents and copyright"),
            ("Insurance Law", "LAW324", "Insurance contracts"),
            ("Tax Law II", "LAW325", "Corporate and VAT"),
            ("Alternative Dispute Resolution", "LAW326", "Mediation and arbitration"),
            ("Moot Court II", "LAW327", "Advanced advocacy"),
        ],
        "4.1": [
            ("Legal Ethics", "LAW411", "Professional responsibility"),
            ("Banking Law", "LAW412", "Financial regulation"),
            ("Mining Law", "LAW413", "Mineral rights and regulation"),
            ("Conveyancing", "LAW414", "Property transfer"),
            ("Clinical Legal Education I", "LAW415", "Legal clinic practice"),
            ("Dissertation I", "LAW416", "Research proposal"),
            ("Cyber Law", "LAW417", "Digital law and privacy"),
        ],
        "4.2": [
            ("Clinical Legal Education II", "LAW421", "Advanced clinic practice"),
            ("Dissertation II", "LAW422", "Research completion"),
            ("Competition Law", "LAW423", "Antitrust regulation"),
            ("International Trade Law", "LAW424", "WTO and trade agreements"),
            ("Media Law", "LAW425", "Press freedom and defamation"),
            ("Legal Drafting", "LAW426", "Contract and statute drafting"),
            ("Law of the Sea", "LAW427", "Maritime law principles"),
        ],
    },
    "BLS": {
        "1.1": [
            ("Introduction to Legal Studies", "BLS111", "Overview of legal systems"),
            ("South African Law", "BLS112", "SA legal framework"),
            ("Legal English", "BLS113", "Legal terminology"),
            ("Political Science I", "BLS114", "Government and politics"),
            ("Communication Skills", "ENG112", "Writing and presentation"),
            ("Introduction to Sociology", "SOC111", "Society and institutions"),
            ("Computer Literacy", "ICT112", "Digital skills for law"),
        ],
        "1.2": [
            ("Constitutional Law", "BLS121", "Constitution and governance"),
            ("Criminal Law", "BLS122", "Crime and punishment"),
            ("Contract Law", "BLS123", "Agreements and obligations"),
            ("Political Science II", "BLS124", "Comparative politics"),
            ("Research Methods", "BLS125", "Legal research skills"),
            ("Human Rights", "BLS126", "Fundamental rights"),
            ("African Politics", "BLS127", "Governance in Africa"),
        ],
        "2.1": [("Labour Law", "BLS211", "Employment law"), ("Property Law", "BLS212", "Real and personal property"), ("Administrative Law", "BLS213", "Public administration law"), ("International Relations", "BLS214", "Global politics"), ("Law of Evidence", "BLS215", "Evidence rules"), ("Public Finance Law", "BLS216", "Government budgets"), ("Legal Ethics", "BLS217", "Professional conduct")],
        "2.2": [("Family Law", "BLS221", "Domestic relations"), ("Company Law", "BLS222", "Business organizations"), ("Environmental Law", "BLS223", "Environmental regulation"), ("Conflict Resolution", "BLS224", "Dispute resolution"), ("Criminology", "BLS225", "Study of crime"), ("Tax Law", "BLS226", "Taxation principles"), ("Dissertation", "BLS227", "Research project")],
        "3.1": [("Advanced Constitutional Law", "BLS311", "Constitutional interpretation"), ("Intellectual Property", "BLS312", "IP rights"), ("Cyber Law", "BLS313", "Internet regulation"), ("Governance & Ethics", "BLS314", "Good governance"), ("Media Law", "BLS315", "Press and broadcasting"), ("Gender & Law", "BLS316", "Women and the law"), ("Internship I", "BLS317", "Workplace attachment")],
        "3.2": [("Comparative Law", "BLS321", "Legal system comparison"), ("International Humanitarian Law", "BLS322", "Laws of war"), ("Mining & Resources Law", "BLS323", "Natural resources"), ("Consumer Protection", "BLS324", "Consumer rights"), ("Legal Writing", "BLS325", "Advanced drafting"), ("Internship II", "BLS326", "Extended placement"), ("Capstone Project", "BLS327", "Final research")],
        "4.1": [("Advanced Criminal Law", "BLS411", "Complex offences"), ("Electoral Law", "BLS412", "Elections and democracy"), ("Regional Integration Law", "BLS413", "AU/SADC frameworks"), ("Law & Development", "BLS414", "Law in developing nations"), ("Transitional Justice", "BLS415", "Post-conflict justice"), ("Dissertation I", "BLS416", "Research phase I"), ("Professional Skills", "BLS417", "Career preparation")],
        "4.2": [("Law & Technology", "BLS421", "Tech regulation"), ("Investment Law", "BLS422", "Foreign investment"), ("Anti-Corruption Law", "BLS423", "Combating corruption"), ("Immigration Law", "BLS424", "Migration regulation"), ("Dissertation II", "BLS425", "Research phase II"), ("Ethics Seminar", "BLS426", "Applied ethics"), ("Exit Seminar", "BLS427", "Capstone presentation")],
    },
    "DPS": {
        "1.1": [("Introduction to Paralegal Studies", "DPS111", "Paralegal role overview"), ("Legal Systems", "DPS112", "Types of legal systems"), ("Communication Skills", "DPS113", "Written communication"), ("Computer Applications", "DPS114", "Office computing"), ("Introduction to Criminal Law", "DPS115", "Crime basics"), ("Legal Terminology", "DPS116", "Legal vocabulary"), ("Ethics for Paralegals", "DPS117", "Professional ethics")],
        "1.2": [("Contract Law Basics", "DPS121", "Simple contracts"), ("Constitutional Law Basics", "DPS122", "Constitution overview"), ("Legal Drafting", "DPS123", "Document preparation"), ("Family Law Basics", "DPS124", "Domestic matters"), ("Labour Law Basics", "DPS125", "Worker rights"), ("Court Procedures", "DPS126", "Court processes"), ("Legal Research", "DPS127", "Finding legal sources")],
        "2.1": [("Property Law Basics", "DPS211", "Property transactions"), ("Evidence Law", "DPS212", "Rules of evidence"), ("Administrative Law", "DPS213", "Government procedures"), ("Human Rights Law", "DPS214", "Rights protection"), ("Litigation Support", "DPS215", "Trial preparation"), ("Internship I", "DPS216", "Work experience"), ("Case Management", "DPS217", "Managing legal cases")],
        "2.2": [("Corporate Law Basics", "DPS221", "Business law"), ("Immigration Procedures", "DPS222", "Immigration forms"), ("Mediation Skills", "DPS223", "Conflict resolution"), ("Legal Office Management", "DPS224", "Running a law office"), ("Internship II", "DPS225", "Extended placement"), ("Portfolio Project", "DPS226", "Final portfolio"), ("Exit Seminar", "DPS227", "Professional preparation")],
        "3.1": [], "3.2": [], "4.1": [], "4.2": [],
    },

    # ── ENGINEERING & APPLIED SCIENCES ──
    "BSCS": {
        "1.1": [
            ("Introduction to Computer Science", "CSC111", "Foundations of computing"),
            ("Programming Fundamentals", "CSC112", "Python programming basics"),
            ("Discrete Mathematics", "MAT111", "Logic, sets, and combinatorics"),
            ("Communication Skills", "ENG113", "Academic writing"),
            ("Introduction to IT", "ICT111", "Hardware, software, networks"),
            ("Calculus I", "MAT112", "Limits, derivatives"),
            ("University Life & Ethics", "ULE112", "Academic integrity"),
        ],
        "1.2": [
            ("Object Oriented Programming", "CSC121", "OOP with Java"),
            ("Data Structures", "CSC122", "Arrays, lists, trees"),
            ("Calculus II", "MAT121", "Integration and series"),
            ("Linear Algebra", "MAT122", "Matrices and vectors"),
            ("Web Development I", "CSC123", "HTML, CSS, JavaScript"),
            ("Digital Electronics", "ELE121", "Logic gates and circuits"),
            ("Statistics I", "STA121", "Descriptive statistics"),
        ],
        "2.1": [
            ("Algorithms and Complexity", "CSC211", "Algorithm design and analysis"),
            ("Database Systems", "CSC212", "SQL and relational databases"),
            ("Computer Architecture", "CSC213", "CPU design and memory"),
            ("Software Engineering I", "CSC214", "SDLC and methodologies"),
            ("Probability & Statistics II", "STA211", "Probability theory"),
            ("Operating Systems I", "CSC215", "Process management"),
            ("Web Development II", "CSC216", "Backend development"),
        ],
        "2.2": [
            ("Operating Systems II", "CSC221", "Memory and file systems"),
            ("Computer Networks I", "CSC222", "TCP/IP and protocols"),
            ("Software Engineering II", "CSC223", "Testing and quality"),
            ("Numerical Methods", "MAT221", "Computational methods"),
            ("Artificial Intelligence I", "CSC224", "Search and reasoning"),
            ("Human Computer Interaction", "CSC225", "UI/UX design principles"),
            ("Mobile App Development", "CSC226", "Android/iOS development"),
        ],
        "3.1": [
            ("Computer Networks II", "CSC311", "Network security"),
            ("Machine Learning", "CSC312", "Supervised and unsupervised learning"),
            ("Compiler Design", "CSC313", "Lexing, parsing, code generation"),
            ("Cloud Computing", "CSC314", "AWS, Azure, containers"),
            ("Cybersecurity", "CSC315", "Threat analysis and defence"),
            ("Project Management", "CSC316", "Agile and Scrum"),
            ("Research Methods", "CSC317", "CS research methodology"),
        ],
        "3.2": [
            ("Distributed Systems", "CSC321", "Scalable architectures"),
            ("Deep Learning", "CSC322", "Neural networks and CNNs"),
            ("Computer Graphics", "CSC323", "Rendering and animation"),
            ("Data Mining", "CSC324", "Pattern discovery"),
            ("IoT Systems", "CSC325", "Embedded and IoT"),
            ("DevOps Practices", "CSC326", "CI/CD and automation"),
            ("Industry Attachment I", "CSC327", "Work placement"),
        ],
        "4.1": [
            ("Final Year Project I", "CSC411", "Project proposal and design"),
            ("Advanced Database Systems", "CSC412", "NoSQL and big data"),
            ("Natural Language Processing", "CSC413", "Text processing and AI"),
            ("Blockchain Technology", "CSC414", "Distributed ledger systems"),
            ("Ethics in Computing", "CSC415", "AI ethics and privacy"),
            ("Entrepreneurship", "BUS411", "Tech startup fundamentals"),
            ("Elective I", "CSC416", "Specialization course"),
        ],
        "4.2": [
            ("Final Year Project II", "CSC421", "Implementation and defence"),
            ("Advanced AI Topics", "CSC422", "Reinforcement learning"),
            ("Quantum Computing Intro", "CSC423", "Quantum algorithms"),
            ("Green Computing", "CSC424", "Sustainable IT"),
            ("Industry Seminar", "CSC425", "Guest lectures and trends"),
            ("Elective II", "CSC426", "Specialization course"),
            ("Exit Portfolio", "CSC427", "Career portfolio"),
        ],
    },
    "BSCE": {
        "1.1": [("Engineering Drawing", "CVE111", "Technical drafting"), ("Engineering Mathematics I", "MAT113", "Calculus for engineers"), ("Introduction to Civil Eng", "CVE112", "Civil engineering overview"), ("Physics I", "PHY111", "Mechanics"), ("Chemistry I", "CHM111", "General chemistry"), ("Communication Skills", "ENG114", "Technical writing"), ("Workshop Technology", "CVE113", "Materials and tools")],
        "1.2": [("Engineering Mathematics II", "MAT123", "Differential equations"), ("Physics II", "PHY121", "Waves and thermodynamics"), ("Surveying I", "CVE121", "Land measurement"), ("Engineering Mechanics I", "CVE122", "Statics"), ("Computer Aided Design", "CVE123", "AutoCAD fundamentals"), ("Materials Science I", "CVE124", "Properties of materials"), ("Environmental Science", "EVS121", "Environmental awareness")],
        "2.1": [("Strength of Materials I", "CVE211", "Stress and strain"), ("Fluid Mechanics I", "CVE212", "Fluid properties and flow"), ("Surveying II", "CVE213", "Advanced surveying"), ("Structural Analysis I", "CVE214", "Beams and frames"), ("Engineering Geology", "CVE215", "Rock and soil types"), ("Construction Materials", "CVE216", "Concrete and steel"), ("Numerical Methods", "MAT214", "Engineering computation")],
        "2.2": [("Strength of Materials II", "CVE221", "Column and beam design"), ("Fluid Mechanics II", "CVE222", "Open channel flow"), ("Geotechnical Eng I", "CVE223", "Soil mechanics"), ("Structural Analysis II", "CVE224", "Indeterminate structures"), ("Highway Engineering I", "CVE225", "Road design"), ("Construction Management", "CVE226", "Project planning"), ("Engineering Economics", "CVE227", "Cost analysis")],
        "3.1": [("Structural Design I", "CVE311", "RC design"), ("Geotechnical Eng II", "CVE312", "Foundation design"), ("Water Resources I", "CVE313", "Hydrology"), ("Highway Engineering II", "CVE314", "Pavement design"), ("Environmental Eng I", "CVE315", "Water treatment"), ("Quantity Surveying", "CVE316", "Cost estimation"), ("Research Methods", "CVE317", "Engineering research")],
        "3.2": [("Structural Design II", "CVE321", "Steel structures"), ("Water Resources II", "CVE322", "Irrigation and dams"), ("Environmental Eng II", "CVE323", "Wastewater treatment"), ("Traffic Engineering", "CVE324", "Traffic flow and signals"), ("Construction Law", "CVE325", "Contracts and liability"), ("Industrial Attachment", "CVE326", "Work placement"), ("Seminar I", "CVE327", "Technical presentations")],
        "4.1": [("Final Year Project I", "CVE411", "Project proposal"), ("Advanced Structural Design", "CVE412", "Prestressed concrete"), ("Urban Planning", "CVE413", "City infrastructure"), ("Bridge Engineering", "CVE414", "Bridge design"), ("Engineering Ethics", "CVE415", "Professional ethics"), ("Elective I", "CVE416", "Specialization"), ("Seminar II", "CVE417", "Research seminar")],
        "4.2": [("Final Year Project II", "CVE421", "Project completion"), ("Earthquake Engineering", "CVE422", "Seismic design"), ("Port & Harbour Eng", "CVE423", "Maritime structures"), ("Green Building Design", "CVE424", "Sustainable construction"), ("Risk Assessment", "CVE425", "Engineering risk"), ("Elective II", "CVE426", "Specialization"), ("Exit Portfolio", "CVE427", "Career portfolio")],
    },
    "BSEE": {
        "1.1": [("Electrical Eng Fundamentals", "ELE111", "Circuit basics"), ("Engineering Mathematics I", "MAT114", "Calculus"), ("Physics I", "PHY112", "Electricity and magnetism"), ("Engineering Drawing", "ELE112", "Electrical schematics"), ("Computer Programming", "ELE113", "C programming"), ("Communication Skills", "ENG115", "Technical communication"), ("Workshop Practice", "ELE114", "Electrical workshop")],
        "1.2": [("Circuit Theory I", "ELE121", "DC and AC circuits"), ("Engineering Mathematics II", "MAT124", "Laplace transforms"), ("Digital Electronics I", "ELE122", "Boolean algebra"), ("Electronics I", "ELE123", "Semiconductor devices"), ("Physics II", "PHY122", "Optics and waves"), ("Technical Writing", "ELE124", "Lab reports"), ("Electromechanics", "ELE125", "Machines intro")],
        "2.1": [("Circuit Theory II", "ELE211", "Network theorems"), ("Electronics II", "ELE212", "Amplifier design"), ("Electromagnetic Theory", "ELE213", "Maxwell's equations"), ("Digital Electronics II", "ELE214", "Microprocessors"), ("Signals & Systems I", "ELE215", "Signal analysis"), ("Measurements", "ELE216", "Instrumentation"), ("Engineering Statistics", "STA212", "Statistical methods")],
        "2.2": [("Power Systems I", "ELE221", "Generation and transmission"), ("Control Systems I", "ELE222", "Feedback control"), ("Signals & Systems II", "ELE223", "Fourier and Z transforms"), ("Communication Systems I", "ELE224", "Modulation techniques"), ("Microcontrollers", "ELE225", "Embedded systems"), ("Energy Conversion", "ELE226", "Machines and drives"), ("Engineering Economics", "ELE227", "Cost-benefit analysis")],
        "3.1": [("Power Systems II", "ELE311", "Power distribution"), ("Control Systems II", "ELE312", "Digital control"), ("Communication Systems II", "ELE313", "Digital communications"), ("Power Electronics", "ELE314", "Converters and inverters"), ("Renewable Energy Systems", "ELE315", "Solar and wind"), ("Research Methods", "ELE316", "Engineering research"), ("Industrial Attachment", "ELE317", "Work placement")],
        "3.2": [("High Voltage Engineering", "ELE321", "Insulation and testing"), ("Electrical Machines II", "ELE322", "Advanced machines"), ("DSP Applications", "ELE323", "Digital signal processing"), ("Antenna & Propagation", "ELE324", "RF engineering"), ("PLC & Automation", "ELE325", "Industrial automation"), ("Seminar I", "ELE326", "Technical presentation"), ("Elective I", "ELE327", "Specialization")],
        "4.1": [("Final Year Project I", "ELE411", "Project proposal"), ("Power System Protection", "ELE412", "Relay systems"), ("Advanced Control", "ELE413", "Nonlinear control"), ("Smart Grid Technology", "ELE414", "Modern power grids"), ("Engineering Management", "ELE415", "Project leadership"), ("Elective II", "ELE416", "Specialization"), ("Ethics in Engineering", "ELE417", "Professional responsibility")],
        "4.2": [("Final Year Project II", "ELE421", "Project completion"), ("Advanced Power Systems", "ELE422", "Power quality"), ("Robotics", "ELE423", "Robot design"), ("Optical Communications", "ELE424", "Fibre optics"), ("Entrepreneurship", "BUS421", "Tech ventures"), ("Elective III", "ELE426", "Specialization"), ("Exit Portfolio", "ELE427", "Career portfolio")],
    },

    # ── HEALTH & ENVIRONMENTAL SCIENCES ──
    "BSNS": {
        "1.1": [("Anatomy & Physiology I", "NUR111", "Body systems"), ("Introduction to Nursing", "NUR112", "Nursing profession"), ("Biochemistry I", "BCH111", "Biological molecules"), ("Psychology for Nurses", "PSY111", "Human behaviour"), ("Communication Skills", "ENG116", "Health communication"), ("Microbiology I", "MIC111", "Bacteria and viruses"), ("Health Ethics", "NUR113", "Bioethics")],
        "1.2": [("Anatomy & Physiology II", "NUR121", "Advanced body systems"), ("Fundamental Nursing", "NUR122", "Basic nursing skills"), ("Pharmacology I", "NUR123", "Drug classification"), ("Nutrition Science", "NUR124", "Diet and health"), ("Sociology for Health", "SOC122", "Health and society"), ("First Aid & Emergency", "NUR125", "Emergency response"), ("Epidemiology I", "NUR126", "Disease patterns")],
        "2.1": [("Medical-Surgical Nursing I", "NUR211", "Adult care"), ("Pharmacology II", "NUR212", "Clinical pharmacology"), ("Community Health Nursing I", "NUR213", "Primary health care"), ("Health Assessment", "NUR214", "Patient assessment"), ("Pathophysiology I", "NUR215", "Disease mechanisms"), ("Research Methods", "NUR216", "Nursing research"), ("Clinical Practicum I", "NUR217", "Hospital placement")],
        "2.2": [("Medical-Surgical Nursing II", "NUR221", "Complex care"), ("Paediatric Nursing I", "NUR222", "Child health"), ("Maternal Health I", "NUR223", "Maternal care"), ("Mental Health Nursing I", "NUR224", "Psychiatric care"), ("Community Health II", "NUR225", "Health promotion"), ("Pathophysiology II", "NUR226", "Advanced pathology"), ("Clinical Practicum II", "NUR227", "Extended placement")],
        "3.1": [("Paediatric Nursing II", "NUR311", "Advanced child care"), ("Maternal Health II", "NUR312", "Obstetric complications"), ("Mental Health Nursing II", "NUR313", "Therapeutic interventions"), ("Nursing Management", "NUR314", "Leadership in nursing"), ("Critical Care Nursing", "NUR315", "ICU nursing"), ("Geriatric Nursing", "NUR316", "Elderly care"), ("Clinical Practicum III", "NUR317", "Specialty placement")],
        "3.2": [("Emergency Nursing", "NUR321", "Trauma care"), ("Oncology Nursing", "NUR322", "Cancer care"), ("Public Health Nursing", "NUR323", "Population health"), ("Advanced Pharmacology", "NUR324", "Prescribing principles"), ("Health Informatics", "NUR325", "Digital health records"), ("Research Project I", "NUR326", "Research proposal"), ("Clinical Practicum IV", "NUR327", "Community placement")],
        "4.1": [("Nursing Leadership", "NUR411", "Administration and policy"), ("Advanced Clinical Practice", "NUR412", "Specialist nursing"), ("Health Policy & Law", "NUR413", "Healthcare regulation"), ("Palliative Care", "NUR414", "End-of-life care"), ("Dissertation I", "NUR415", "Research implementation"), ("Clinical Elective I", "NUR416", "Specialization"), ("Preceptorship I", "NUR417", "Professional mentoring")],
        "4.2": [("Professional Practice", "NUR421", "Transition to practice"), ("Dissertation II", "NUR422", "Research completion"), ("Global Health", "NUR423", "International nursing"), ("Quality Improvement", "NUR424", "Patient safety"), ("Clinical Elective II", "NUR425", "Advanced specialization"), ("Preceptorship II", "NUR426", "Leadership placement"), ("Exit Examination", "NUR427", "Licensing preparation")],
    },
    "BSES": {
        "1.1": [("Introduction to Environmental Science", "EVS111", "Environment overview"), ("Biology I", "BIO111", "Cell biology"), ("Chemistry I", "CHM112", "Inorganic chemistry"), ("Mathematics I", "MAT115", "Applied mathematics"), ("Communication Skills", "ENG117", "Scientific writing"), ("Geography I", "GEO111", "Physical geography"), ("Ecology I", "EVS112", "Ecosystem basics")],
        "1.2": [("Biology II", "BIO121", "Genetics and evolution"), ("Chemistry II", "CHM122", "Organic chemistry"), ("Statistics I", "STA122", "Data analysis"), ("Geography II", "GEO121", "Human geography"), ("Ecology II", "EVS121B", "Population ecology"), ("Soil Science I", "EVS122", "Soil properties"), ("Climate Science", "EVS123", "Weather and climate")],
        "2.1": [("Environmental Chemistry", "EVS211", "Pollution chemistry"), ("Biodiversity Conservation", "EVS212", "Species protection"), ("Water Resources Mgmt", "EVS213", "Water quality"), ("GIS & Remote Sensing I", "EVS214", "Spatial analysis"), ("Environmental Law", "EVS215", "Environmental legislation"), ("Soil Science II", "EVS216", "Soil management"), ("Research Methods", "EVS217", "Scientific research")],
        "2.2": [("Waste Management", "EVS221", "Solid and hazardous waste"), ("Environmental Impact Assessment", "EVS222", "EIA methodology"), ("Air Quality Management", "EVS223", "Air pollution"), ("GIS & Remote Sensing II", "EVS224", "Advanced mapping"), ("Marine Biology", "EVS225", "Ocean ecosystems"), ("Forestry Science", "EVS226", "Forest management"), ("Field Studies I", "EVS227", "Field trip")],
        "3.1": [("Climate Change Science", "EVS311", "Global warming"), ("Wildlife Management", "EVS312", "Conservation planning"), ("Aquatic Ecology", "EVS313", "Freshwater systems"), ("Environmental Toxicology", "EVS314", "Toxic substances"), ("Sustainable Development", "EVS315", "SDGs and planning"), ("Environmental Policy", "EVS316", "Policy analysis"), ("Field Studies II", "EVS317", "Extended fieldwork")],
        "3.2": [("Land Use Planning", "EVS321", "Spatial planning"), ("Restoration Ecology", "EVS322", "Habitat restoration"), ("Energy & Environment", "EVS323", "Renewable energy impacts"), ("Environmental Monitoring", "EVS324", "Data collection"), ("Disaster Management", "EVS325", "Natural disasters"), ("Industrial Attachment", "EVS326", "Work placement"), ("Research Project I", "EVS327", "Proposal")],
        "4.1": [("Advanced Ecology", "EVS411", "Ecosystem dynamics"), ("Environmental Management Systems", "EVS412", "ISO 14001"), ("Urban Ecology", "EVS413", "Cities and nature"), ("Carbon Management", "EVS414", "Carbon footprint"), ("Dissertation I", "EVS415", "Research phase I"), ("Elective I", "EVS416", "Specialization"), ("Professional Ethics", "EVS417", "Environmental ethics")],
        "4.2": [("Final Year Project", "EVS421", "Research completion"), ("Environmental Governance", "EVS422", "International frameworks"), ("Green Economy", "EVS423", "Sustainable business"), ("Elective II", "EVS424", "Specialization"), ("Capstone Seminar", "EVS425", "Exit presentation"), ("Internship Report", "EVS426", "Placement report"), ("Portfolio", "EVS427", "Career portfolio")],
    },
    "BPHA": {
        "1.1": [("Introduction to Pharmacy", "PHA111", "Pharmacy profession"), ("Biology for Pharmacy", "BIO112", "Human biology"), ("Chemistry for Pharmacy", "CHM113", "Pharmaceutical chemistry"), ("Mathematics for Pharmacy", "MAT116", "Calculations"), ("Communication Skills", "ENG118", "Health communication"), ("Anatomy & Physiology I", "PHA112", "Body structure"), ("Ethics in Pharmacy", "PHA113", "Professional ethics")],
        "1.2": [("Pharmaceutical Chemistry I", "PHA121", "Drug chemistry"), ("Anatomy & Physiology II", "PHA122", "Organ systems"), ("Pharmaceutics I", "PHA123", "Dosage forms"), ("Biochemistry", "BCH121", "Metabolic pathways"), ("Microbiology", "MIC121", "Pathogens"), ("Pharmacognosy I", "PHA124", "Natural products"), ("Statistics", "STA123", "Biostatistics")],
        "2.1": [("Pharmacology I", "PHA211", "Drug action"), ("Pharmaceutical Chemistry II", "PHA212", "Drug synthesis"), ("Pharmaceutics II", "PHA213", "Formulation"), ("Pathophysiology", "PHA214", "Disease processes"), ("Pharmacognosy II", "PHA215", "Herbal medicine"), ("Pharmacy Law", "PHA216", "Drug regulation"), ("Clinical Practicum I", "PHA217", "Dispensing practice")],
        "2.2": [("Pharmacology II", "PHA221", "Systems pharmacology"), ("Medicinal Chemistry", "PHA222", "Drug design"), ("Physical Pharmacy", "PHA223", "Physicochemical properties"), ("Immunology", "PHA224", "Immune system"), ("Toxicology", "PHA225", "Poisoning and treatment"), ("Drug Information", "PHA226", "Drug literature"), ("Clinical Practicum II", "PHA227", "Hospital pharmacy")],
        "3.1": [("Clinical Pharmacy I", "PHA311", "Patient care"), ("Pharmacokinetics", "PHA312", "ADME"), ("Pharmaceutical Microbiology", "PHA313", "Sterile products"), ("Pharmacoepidemiology", "PHA314", "Drug safety"), ("Industrial Pharmacy", "PHA315", "Manufacturing"), ("Research Methods", "PHA316", "Pharmacy research"), ("Clinical Practicum III", "PHA317", "Specialty practice")],
        "3.2": [("Clinical Pharmacy II", "PHA321", "Therapeutic monitoring"), ("Biopharmaceutics", "PHA322", "Drug absorption"), ("Quality Assurance", "PHA323", "GMP and QC"), ("Pharmacoeconomics", "PHA324", "Drug costs"), ("Drug Delivery Systems", "PHA325", "Novel dosage forms"), ("Hospital Pharmacy Mgmt", "PHA326", "Pharmacy administration"), ("Clinical Practicum IV", "PHA327", "Community pharmacy")],
        "4.1": [("Advanced Clinical Pharmacy", "PHA411", "Complex therapeutics"), ("Pharmaceutical Care", "PHA412", "Patient counselling"), ("Radiopharmacy", "PHA413", "Nuclear medicine"), ("Dissertation I", "PHA414", "Research proposal"), ("Regulatory Affairs", "PHA415", "Drug registration"), ("Elective I", "PHA416", "Specialization"), ("Preceptorship I", "PHA417", "Professional mentoring")],
        "4.2": [("Dissertation II", "PHA421", "Research completion"), ("Professional Practice", "PHA422", "Pharmacy management"), ("Public Health Pharmacy", "PHA423", "Essential medicines"), ("Elective II", "PHA424", "Specialization"), ("Pharmacy Ethics Seminar", "PHA425", "Case studies"), ("Preceptorship II", "PHA426", "Advanced placement"), ("Licensing Exam Prep", "PHA427", "Board preparation")],
    },

    # ── SOCIAL SCIENCES, THEOLOGY & HUMANITIES ──
    "BATRS": {
        "1.1": [("Old Testament Studies I", "THE111", "Pentateuch"), ("Introduction to Theology", "THE112", "Theological foundations"), ("Church History I", "THE113", "Early church"), ("Greek I", "THE114", "Biblical Greek"), ("Communication Skills", "ENG119", "Academic writing"), ("Philosophy of Religion", "PHI112", "Faith and reason"), ("African Traditional Religion", "THE115", "Indigenous belief systems")],
        "1.2": [("New Testament Studies I", "THE121", "Gospels"), ("Systematic Theology I", "THE122", "Doctrine of God"), ("Church History II", "THE123", "Reformation"), ("Hebrew I", "THE124", "Biblical Hebrew"), ("Ethics", "THE125", "Christian ethics"), ("World Religions", "THE126", "Comparative religion"), ("Pastoral Care I", "THE127", "Counselling basics")],
        "2.1": [("Old Testament Studies II", "THE211", "Prophets"), ("Systematic Theology II", "THE212", "Christology"), ("Homiletics I", "THE213", "Preaching"), ("Greek II", "THE214", "Exegesis"), ("African Theology", "THE215", "Contextual theology"), ("Research Methods", "THE216", "Theological research"), ("Mission Studies", "THE217", "Missiology")],
        "2.2": [("New Testament Studies II", "THE221", "Pauline letters"), ("Practical Theology", "THE222", "Ministry practice"), ("Hebrew II", "THE223", "OT exegesis"), ("Liberation Theology", "THE224", "Justice and faith"), ("Pastoral Care II", "THE225", "Advanced counselling"), ("Worship & Liturgy", "THE226", "Spiritual practices"), ("Field Education I", "THE227", "Church placement")],
        "3.1": [("Systematic Theology III", "THE311", "Pneumatology"), ("Homiletics II", "THE312", "Advanced preaching"), ("Theology & Gender", "THE313", "Feminist theology"), ("Ecumenism", "THE314", "Christian unity"), ("Theology & Social Justice", "THE315", "Public theology"), ("Dissertation I", "THE316", "Research proposal"), ("Field Education II", "THE317", "Extended ministry")],
        "3.2": [("Church Administration", "THE321", "Organizational management"), ("Theology & Science", "THE322", "Faith-science dialogue"), ("Religious Education", "THE323", "Teaching religion"), ("Interfaith Dialogue", "THE324", "Cross-religious engagement"), ("Dissertation II", "THE325", "Research completion"), ("Elective I", "THE326", "Specialization"), ("Capstone Seminar", "THE327", "Exit presentation")],
        "4.1": [("Advanced OT Studies", "THE411", "Wisdom literature"), ("Advanced NT Studies", "THE412", "Revelation"), ("Contemporary Theology", "THE413", "Modern theologians"), ("Missional Leadership", "THE414", "Church leadership"), ("Dissertation III", "THE415", "Final research"), ("Elective II", "THE416", "Specialization"), ("Professional Ethics", "THE417", "Ministerial ethics")],
        "4.2": [("Theology & Culture", "THE421", "Inculturation"), ("Pentecostalism", "THE422", "Charismatic movements"), ("Theology & Development", "THE423", "Faith and development"), ("Advanced Pastoral Care", "THE424", "Crisis counselling"), ("Final Dissertation", "THE425", "Defence"), ("Ministry Internship", "THE426", "Full-time ministry"), ("Exit Portfolio", "THE427", "Career preparation")],
    },
    "BAPSY": {
        "1.1": [("Introduction to Psychology", "PSY112", "Psychological foundations"), ("Developmental Psychology I", "PSY113", "Child development"), ("Biology for Psychology", "BIO113", "Neuroanatomy basics"), ("Philosophy", "PHI113", "Critical thinking"), ("Communication Skills", "ENG120", "Academic writing"), ("Sociology I", "SOC112", "Social structures"), ("Statistics for Psychology I", "STA124", "Data basics")],
        "1.2": [("Social Psychology I", "PSY121", "Group behaviour"), ("Developmental Psychology II", "PSY122", "Adolescence to old age"), ("Cognitive Psychology I", "PSY123", "Perception and memory"), ("Statistics for Psychology II", "STA125", "Inferential statistics"), ("Personality Psychology", "PSY124", "Personality theories"), ("Health Psychology I", "PSY125", "Health behaviour"), ("Introduction to Counselling", "PSY126", "Helping skills")],
        "2.1": [("Abnormal Psychology I", "PSY211", "Psychopathology"), ("Research Methods I", "PSY212", "Experimental design"), ("Cognitive Psychology II", "PSY213", "Language and thought"), ("Neuropsychology I", "PSY214", "Brain and behaviour"), ("Social Psychology II", "PSY215", "Attitudes and persuasion"), ("Organizational Psychology", "PSY216", "Work behaviour"), ("Psychometrics I", "PSY217", "Testing principles")],
        "2.2": [("Abnormal Psychology II", "PSY221", "Treatment approaches"), ("Research Methods II", "PSY222", "Qualitative methods"), ("Neuropsychology II", "PSY223", "Clinical neuropsychology"), ("Forensic Psychology", "PSY224", "Law and psychology"), ("Community Psychology", "PSY225", "Social intervention"), ("Health Psychology II", "PSY226", "Behavioural medicine"), ("Psychometrics II", "PSY227", "Test construction")],
        "3.1": [("Clinical Psychology I", "PSY311", "Assessment"), ("Counselling Psychology I", "PSY312", "Therapeutic approaches"), ("Child & Adolescent Psychology", "PSY313", "Youth mental health"), ("Cross-Cultural Psychology", "PSY314", "Culture and mind"), ("Positive Psychology", "PSY315", "Well-being science"), ("Dissertation I", "PSY316", "Research proposal"), ("Practicum I", "PSY317", "Clinical observation")],
        "3.2": [("Clinical Psychology II", "PSY321", "Intervention"), ("Counselling Psychology II", "PSY322", "Advanced techniques"), ("Psychology & Education", "PSY323", "Educational psychology"), ("Trauma Psychology", "PSY324", "PTSD and recovery"), ("Substance Abuse", "PSY325", "Addiction psychology"), ("Dissertation II", "PSY326", "Data collection"), ("Practicum II", "PSY327", "Supervised practice")],
        "4.1": [("Advanced Clinical Psych", "PSY411", "Complex cases"), ("Psychopharmacology", "PSY412", "Psychiatric medication"), ("Ethics in Psychology", "PSY413", "Professional ethics"), ("Psychology & HIV/AIDS", "PSY414", "Counselling for HIV"), ("Dissertation III", "PSY415", "Analysis and write-up"), ("Elective I", "PSY416", "Specialization"), ("Internship I", "PSY417", "Placement")],
        "4.2": [("Professional Practice", "PSY421", "Registration preparation"), ("Advanced Research", "PSY422", "Publication skills"), ("Psychology & Gender", "PSY423", "Gender issues"), ("Final Dissertation", "PSY424", "Defence"), ("Elective II", "PSY425", "Specialization"), ("Internship II", "PSY426", "Extended placement"), ("Exit Portfolio", "PSY427", "Career preparation")],
    },
    "BAIR": {
        "1.1": [("Introduction to International Relations", "IR111", "Global politics"), ("Political Science I", "POL111", "Government systems"), ("History of World Politics", "IR112", "Modern history"), ("Economics I", "ECO111", "Microeconomics"), ("Communication Skills", "ENG121", "Academic writing"), ("Sociology I", "SOC113", "Social institutions"), ("African History", "HIS111", "Pre-colonial Africa")],
        "1.2": [("International Relations Theory", "IR121", "Realism and liberalism"), ("Political Science II", "POL121", "Comparative politics"), ("Economics II", "ECO121", "Macroeconomics"), ("Geography of Development", "GEO122", "Global development"), ("African Politics", "IR122", "Continental governance"), ("Research Methods I", "IR123", "Social research"), ("Diplomatic History", "IR124", "History of diplomacy")],
        "2.1": [("Foreign Policy Analysis", "IR211", "Decision making"), ("International Organizations", "IR212", "UN and AU systems"), ("International Political Economy", "IR213", "Trade and finance"), ("Conflict Resolution", "IR214", "Peace studies"), ("International Law I", "IR215", "Public international law"), ("Statistics for Social Science", "STA213", "Quantitative methods"), ("Gender & IR", "IR216", "Feminist IR")],
        "2.2": [("Security Studies", "IR221", "National and human security"), ("Regionalism", "IR222", "SADC, EU, ASEAN"), ("Development Studies", "IR223", "Development theory"), ("International Law II", "IR224", "Treaties and courts"), ("Diplomacy & Negotiation", "IR225", "Diplomatic practice"), ("Media & IR", "IR226", "Information and power"), ("Research Methods II", "IR227", "Qualitative methods")],
        "3.1": [("Global Governance", "IR311", "Multilateral institutions"), ("African International Relations", "IR312", "Africa in global politics"), ("Human Rights", "IR313", "International HR mechanisms"), ("Terrorism & Counter-Terrorism", "IR314", "Non-state threats"), ("Environmental Politics", "IR315", "Climate diplomacy"), ("Dissertation I", "IR316", "Research proposal"), ("Internship I", "IR317", "Placement")],
        "3.2": [("Strategic Studies", "IR321", "Military and strategy"), ("Peacebuilding", "IR322", "Post-conflict reconstruction"), ("Migration & Refugees", "IR323", "Forced displacement"), ("Cyber Politics", "IR324", "Digital geopolitics"), ("Chinese/Asian Politics", "IR325", "Asia in world affairs"), ("Dissertation II", "IR326", "Data collection"), ("Internship II", "IR327", "Extended placement")],
        "4.1": [("Advanced IR Theory", "IR411", "Constructivism and postcolonialism"), ("US Foreign Policy", "IR412", "American power"), ("Middle East Politics", "IR413", "Regional dynamics"), ("Intelligence Studies", "IR414", "Espionage and analysis"), ("Dissertation III", "IR415", "Analysis"), ("Elective I", "IR416", "Specialization"), ("Model UN", "IR417", "Simulation exercise")],
        "4.2": [("Global Political Economy", "IR421", "Financial crises"), ("Southern African Politics", "IR422", "Regional dynamics"), ("Nuclear Politics", "IR423", "Non-proliferation"), ("Final Dissertation", "IR424", "Defence"), ("Elective II", "IR425", "Specialization"), ("Professional Development", "IR426", "Career skills"), ("Exit Portfolio", "IR427", "Career preparation")],
    },

    # ── BUSINESS & MANAGEMENT SCIENCES ──
    "BCACC": {
        "1.1": [("Financial Accounting I", "ACC111", "Accounting fundamentals"), ("Business Mathematics", "MAT117", "Quantitative methods"), ("Introduction to Business", "BUS111", "Business environment"), ("Business Communication", "ENG122", "Professional communication"), ("Microeconomics", "ECO112", "Markets and prices"), ("Information Systems I", "ISY111", "Business computing"), ("Business Law I", "LAW118", "Legal environment")],
        "1.2": [("Financial Accounting II", "ACC121", "Advanced bookkeeping"), ("Business Statistics", "STA126", "Statistical methods"), ("Macroeconomics", "ECO122", "National economy"), ("Management I", "MGT121", "Management principles"), ("Information Systems II", "ISY121", "Databases"), ("Cost Accounting I", "ACC122", "Cost classification"), ("Business Law II", "LAW128", "Contracts and liability")],
        "2.1": [("Financial Accounting III", "ACC211", "Company accounts"), ("Management Accounting I", "ACC212", "Budgeting"), ("Taxation I", "TAX211", "Personal tax"), ("Auditing I", "AUD211", "Audit principles"), ("Corporate Finance I", "FIN211", "Financial management"), ("Business Ethics", "BUS211", "Ethical practices"), ("Commercial Law", "LAW218", "Sale of goods")],
        "2.2": [("Financial Accounting IV", "ACC221", "Group accounts"), ("Management Accounting II", "ACC222", "Decision making"), ("Taxation II", "TAX221", "Corporate tax"), ("Auditing II", "AUD221", "Internal audit"), ("Corporate Finance II", "FIN221", "Investment appraisal"), ("Entrepreneurship", "BUS221", "Starting a business"), ("Information Systems III", "ISY221", "ERP systems")],
        "3.1": [("Advanced Financial Accounting", "ACC311", "IAS/IFRS"), ("Advanced Management Accounting", "ACC312", "Strategic costing"), ("Advanced Taxation", "TAX311", "Tax planning"), ("Advanced Auditing", "AUD311", "Risk-based audit"), ("Corporate Governance", "ACC313", "Board and compliance"), ("Research Methods", "ACC314", "Accounting research"), ("Industry Attachment", "ACC315", "Work placement")],
        "3.2": [("Public Sector Accounting", "ACC321", "Government accounting"), ("Forensic Accounting", "ACC322", "Fraud investigation"), ("International Accounting", "ACC323", "Global standards"), ("Financial Analysis", "ACC324", "Ratio analysis"), ("Accounting Information Systems", "ACC325", "IT and accounting"), ("Dissertation I", "ACC326", "Research proposal"), ("Seminar I", "ACC327", "Professional development")],
        "4.1": [("Strategic Management Accounting", "ACC411", "Balanced scorecard"), ("Advanced Auditing II", "AUD411", "Assurance services"), ("Advanced Tax Planning", "TAX411", "Estate planning"), ("Dissertation II", "ACC412", "Research implementation"), ("Professional Ethics", "ACC413", "IESBA code"), ("Elective I", "ACC414", "Specialization"), ("CPA Preparation I", "ACC415", "Board exam prep")],
        "4.2": [("Final Dissertation", "ACC421", "Research completion"), ("Integrated Case Study", "ACC422", "Comprehensive assessment"), ("Corporate Reporting", "ACC423", "Annual reports"), ("Elective II", "ACC424", "Specialization"), ("CPA Preparation II", "ACC425", "Advanced prep"), ("Professional Seminar", "ACC426", "Career readiness"), ("Exit Portfolio", "ACC427", "Career portfolio")],
    },
    "BCMKT": {
        "1.1": [("Principles of Marketing", "MKT111", "Marketing fundamentals"), ("Business Mathematics", "MAT118", "Quantitative skills"), ("Introduction to Business", "BUS112", "Business overview"), ("Business Communication", "ENG123", "Writing for business"), ("Microeconomics", "ECO113", "Supply and demand"), ("Information Technology", "ISY112", "Digital literacy"), ("Consumer Behaviour I", "MKT112", "Buying decisions")],
        "1.2": [("Marketing Management", "MKT121", "Planning and strategy"), ("Business Statistics", "STA127", "Market research stats"), ("Macroeconomics", "ECO123", "Economic indicators"), ("Management Principles", "MGT122", "Organizational management"), ("Financial Accounting I", "ACC123", "Accounting basics"), ("Digital Marketing I", "MKT122", "Online marketing basics"), ("Business Law", "LAW129", "Legal framework")],
        "2.1": [("Marketing Research", "MKT211", "Data collection and analysis"), ("Brand Management", "MKT212", "Building brands"), ("Sales Management", "MKT213", "Sales force management"), ("Services Marketing", "MKT214", "Service industries"), ("Digital Marketing II", "MKT215", "SEO and SEM"), ("Business Ethics", "BUS212", "Ethical marketing"), ("Integrated Marketing Communications", "MKT216", "Advertising and PR")],
        "2.2": [("International Marketing", "MKT221", "Global markets"), ("Retail Marketing", "MKT222", "Retail management"), ("Product Development", "MKT223", "Innovation and NPD"), ("Social Media Marketing", "MKT224", "Content and engagement"), ("Supply Chain Management", "MKT225", "Logistics"), ("Customer Relationship Mgmt", "MKT226", "CRM systems"), ("Entrepreneurship", "BUS222", "Business ventures")],
        "3.1": [("Strategic Marketing", "MKT311", "Competitive strategy"), ("Marketing Analytics", "MKT312", "Data-driven marketing"), ("E-Commerce", "MKT313", "Online business"), ("Advertising Management", "MKT314", "Campaign planning"), ("B2B Marketing", "MKT315", "Industrial marketing"), ("Research Methods", "MKT316", "Marketing research"), ("Industry Attachment", "MKT317", "Work placement")],
        "3.2": [("Public Relations", "MKT321", "Corporate communication"), ("Event Marketing", "MKT322", "Experiential marketing"), ("Marketing Law & Ethics", "MKT323", "Consumer protection"), ("Advanced Digital Marketing", "MKT324", "Marketing automation"), ("African Marketing", "MKT325", "Emerging markets"), ("Dissertation I", "MKT326", "Research proposal"), ("Seminar", "MKT327", "Industry trends")],
        "4.1": [("Advanced Strategic Marketing", "MKT411", "Market leadership"), ("Global Brand Strategy", "MKT412", "International branding"), ("Marketing Innovation", "MKT413", "Disruptive marketing"), ("Dissertation II", "MKT414", "Research completion"), ("Professional Ethics", "MKT415", "Marketing responsibility"), ("Elective I", "MKT416", "Specialization"), ("Consulting Project", "MKT417", "Client-based project")],
        "4.2": [("Final Dissertation", "MKT421", "Defence"), ("Integrated Marketing Campaign", "MKT422", "Capstone project"), ("Luxury Marketing", "MKT423", "Premium brands"), ("Elective II", "MKT424", "Specialization"), ("Professional Development", "MKT425", "Career preparation"), ("Portfolio", "MKT426", "Work samples"), ("Exit Seminar", "MKT427", "Industry readiness")],
    },
    "BBAMGT": {
        "1.1": [("Introduction to Management", "MGT111", "Management principles"), ("Business Mathematics", "MAT119", "Quantitative methods"), ("Introduction to Business", "BUS113", "Business fundamentals"), ("Business Communication", "ENG124", "Professional writing"), ("Microeconomics", "ECO114", "Economic principles"), ("Information Technology", "ISY113", "Digital skills"), ("Business Law I", "LAW119", "Legal basics")],
        "1.2": [("Organizational Behaviour", "MGT121", "People in organizations"), ("Business Statistics", "STA128", "Applied statistics"), ("Macroeconomics", "ECO124", "National economy"), ("Financial Accounting I", "ACC124", "Accounting basics"), ("Marketing Principles", "MKT123", "Marketing basics"), ("Human Resources Mgmt I", "HRM121", "HR functions"), ("Business Law II", "LAW130", "Company law")],
        "2.1": [("Operations Management", "MGT211", "Production and quality"), ("Financial Management I", "FIN212", "Corporate finance basics"), ("Human Resources Mgmt II", "HRM211", "Talent management"), ("Business Strategy I", "MGT212", "Strategic analysis"), ("Project Management I", "MGT213", "Planning and scheduling"), ("Management Information Systems", "ISY211", "IT and business"), ("Business Ethics", "BUS213", "Ethical leadership")],
        "2.2": [("Supply Chain Management", "MGT221", "Logistics and procurement"), ("Financial Management II", "FIN222", "Investment analysis"), ("Industrial Relations", "HRM221", "Labour relations"), ("Business Strategy II", "MGT222", "Competitive advantage"), ("Project Management II", "MGT223", "Risk and quality"), ("Entrepreneurship", "BUS223", "Small business management"), ("Change Management", "MGT224", "Organizational change")],
        "3.1": [("Leadership Studies", "MGT311", "Leadership theory"), ("International Business", "MGT312", "Global operations"), ("Total Quality Management", "MGT313", "Quality systems"), ("Public Administration", "MGT314", "Government management"), ("Innovation Management", "MGT315", "Creativity and innovation"), ("Research Methods", "MGT316", "Business research"), ("Industry Attachment", "MGT317", "Work placement")],
        "3.2": [("Strategic Management", "MGT321", "Strategic planning"), ("Performance Management", "MGT322", "KPIs and metrics"), ("Corporate Social Responsibility", "MGT323", "Sustainability"), ("Risk Management", "MGT324", "Enterprise risk"), ("Negotiations", "MGT325", "Business negotiation"), ("Dissertation I", "MGT326", "Research proposal"), ("Seminar", "MGT327", "Management topics")],
        "4.1": [("Advanced Strategic Management", "MGT411", "Blue ocean strategy"), ("Corporate Governance", "MGT412", "Board management"), ("Management Consulting", "MGT413", "Advisory skills"), ("Dissertation II", "MGT414", "Research completion"), ("Professional Ethics", "MGT415", "Business integrity"), ("Elective I", "MGT416", "Specialization"), ("Executive Skills", "MGT417", "C-suite preparation")],
        "4.2": [("Final Dissertation", "MGT421", "Defence"), ("Business Simulation", "MGT422", "Capstone game"), ("Global Business Strategy", "MGT423", "International strategy"), ("Elective II", "MGT424", "Specialization"), ("Professional Development", "MGT425", "Career readiness"), ("Portfolio", "MGT426", "Work portfolio"), ("Exit Seminar", "MGT427", "Industry preparation")],
    },
}
